gpu-context=waylandvk
vo=gpu-next
hwdec=vaapi

profile=high-quality

# scale=ewa_lanczossharp
# cscale=ewa_lanczossharp

deband=yes

# video-sync=audio
# interpolation=no
# tscale=oversample

vd-lavc-threads=4
demuxer-max-bytes=512MiB
cache=yes

save-position-on-quit=yes
watch-later-directory=~/.config/mpv/watch_later

fullscreen=no

sub-auto=fuzzy
slang=en
sub-font-size=42
sub-border-size=2
blend-subtitles=yes

volume=100
audio-file-auto=fuzzy

screenshot-format=png
screenshot-directory=~/Pictures/mpv

ytdl-format=bestvideo[height<=2160]+bestaudio/best

osc=yes
osd-bar=yes
