set -g base-index 1
setw -g pane-base-index 1
set -g default-terminal "xterm-ghostty"
set -ag terminal-overrides ",xterm-ghostty:Tc"
set-window-option -g mode-keys vi
setw -g mouse on

set -g status-style bg=default,fg=purple
